// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/ramnath.1998/vyaaparjunction/ent/runtime.go

const (
	Version = "v0.12.6-0.20231126115850-536984eeeff2"           // Version of ent codegen.
	Sum     = "h1:CRNHOGIx0vlDt5V8dzv4LJifDan0cRJ8W0D9KeBeXH8=" // Sum of ent codegen.
)
