// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/ramnath.1998/vyaaparjunction/ent/product"
	"github.com/ramnath.1998/vyaaparjunction/ent/productcategory"
	"github.com/ramnath.1998/vyaaparjunction/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	productFields := schema.Product{}.Fields()
	_ = productFields
	// productDescProductName is the schema descriptor for productName field.
	productDescProductName := productFields[0].Descriptor()
	// product.ProductNameValidator is a validator for the "productName" field. It is called by the builders before save.
	product.ProductNameValidator = productDescProductName.Validators[0].(func(string) error)
	// productDescIdentifier is the schema descriptor for Identifier field.
	productDescIdentifier := productFields[1].Descriptor()
	// product.DefaultIdentifier holds the default value on creation for the Identifier field.
	product.DefaultIdentifier = productDescIdentifier.Default.(func() uuid.UUID)
	// productDescCreatedOn is the schema descriptor for createdOn field.
	productDescCreatedOn := productFields[2].Descriptor()
	// product.DefaultCreatedOn holds the default value on creation for the createdOn field.
	product.DefaultCreatedOn = productDescCreatedOn.Default.(func() time.Time)
	productcategoryFields := schema.ProductCategory{}.Fields()
	_ = productcategoryFields
	// productcategoryDescCategoryName is the schema descriptor for categoryName field.
	productcategoryDescCategoryName := productcategoryFields[0].Descriptor()
	// productcategory.CategoryNameValidator is a validator for the "categoryName" field. It is called by the builders before save.
	productcategory.CategoryNameValidator = productcategoryDescCategoryName.Validators[0].(func(string) error)
	// productcategoryDescIdentifier is the schema descriptor for Identifier field.
	productcategoryDescIdentifier := productcategoryFields[1].Descriptor()
	// productcategory.DefaultIdentifier holds the default value on creation for the Identifier field.
	productcategory.DefaultIdentifier = productcategoryDescIdentifier.Default.(func() uuid.UUID)
	// productcategoryDescCreatedOn is the schema descriptor for createdOn field.
	productcategoryDescCreatedOn := productcategoryFields[2].Descriptor()
	// productcategory.DefaultCreatedOn holds the default value on creation for the createdOn field.
	productcategory.DefaultCreatedOn = productcategoryDescCreatedOn.Default.(func() time.Time)
}
