// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)

// ProductCategory is the predicate function for productcategory builders.
type ProductCategory func(*sql.Selector)
